[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "physmetrics-weather"
version = "0.1.0"
description = "Evaluation framework for physical consistency of AI weather models"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Emma Kasteleyn" },
    { name = "Timo Maier", email = "timo.maier@tum.de" }
]
dependencies = [
    "numpy",
    "pandas",
    "xarray",
    "dask",
    "matplotlib",
    "seaborn",
    "scipy",
    "zarr",
    "gcsfs",
    "pyshtools",
    "tqdm"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
    "sphinx>=5.0",
    "sphinx-rtd-theme",
    "myst-parser"
]
docs = [
    "sphinx>=5.0",
    "sphinx-rtd-theme",
    "myst-parser"
]

[project.scripts]
physmetrics-run = "physmetrics_weather.run_all_metrics:main"
physmetrics-plot = "physmetrics_weather.plot_neurips_metrics:main"

[tool.setuptools.packages.find]
where = ["src"]
