#!/usr/bin/env python
"""Plotting & Visualization Script for Physics Metrics.

Reads long-format CSV files generated by `physmetrics-run` and time-series CSVs,
producing publication-ready figures for conservation drift, balance errors, kinetic
energy spectra, and effective resolution.

Ensemble / Probabilistic Support:
    Handles CSV outputs with `ensemble_member` columns automatically. Aggregates
    ensemble members by computing mean and standard deviation shading or individual
    realization trajectories.

Output Plots:
    1. ts_dry_mass_Eg.png       — Global dry air mass drift timeseries
    2. ts_water_mass_kg.png     — Global water mass drift timeseries
    3. ts_total_energy_J.png    — Global total energy drift timeseries
    4. ts_hydrostatic_rmse.png  — Hydrostatic balance error timeseries
    5. ts_geostrophic_rmse.png  — Geostrophic balance error timeseries
    6. spectra_ke_*.png         — Kinetic energy spectra at forecast lead times

Usage:
    physmetrics-plot --results-dir ./results --outdir ./plots
"""

from __future__ import annotations

import argparse
import glob
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Union

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


# ============================================================================
# Color Palettes & Plotting Theme
# ============================================================================

MODEL_COLORS: Dict[str, str] = {
    "ERA5": "#2c3e50",
    "IFS": "#7f8c8d",
    "Pangu": "#e74c3c",
    "GraphCast": "#2980b9",
    "FourCastNet": "#2ecc71",
    "FuXi": "#9b59b6",
    "Aurora": "#e67e22",
    "Model": "#d35400",
}

DEFAULT_PALETTE: List[str] = [
    "#e74c3c", "#2980b9", "#2ecc71", "#9b59b6",
    "#e67e22", "#16a085", "#f39c12", "#c0392b",
]


@dataclass
class PlotterConfig:
    """Configuration container for plot styling and layout.

    Attributes:
        results_dir: Path to directory containing output CSV files.
        outdir: Destination directory for rendered figure files.
        reference_label: Reference dataset label override.
        style: Seaborn plot theme style.
        dpi: Figure resolution DPI for image export.
        file_format: Output image format ('png', 'pdf', 'svg').
    """

    results_dir: Path
    outdir: Path
    reference_label: str = "auto"
    style: str = "whitegrid"
    dpi: int = 300
    file_format: str = "png"


# ============================================================================
# Helper Functions
# ============================================================================

def infer_reference_label(results_dir: Path, override: str = "auto") -> str:
    """Infer reference dataset label from path name or return override.

    Args:
        results_dir: Path to directory containing evaluation output files.
        override: Optional reference label override ('auto', 'ERA5', or 'IFS').

    Returns:
        The inferred or overridden reference dataset label string.
    """
    if override != "auto":
        return override
    name_lower = str(results_dir).lower()
    if "ifs" in name_lower:
        return "IFS"
    return "ERA5"


def pretty_region_name(region: str) -> str:
    """Format geographical region keys into human-readable labels.

    Args:
        region: Region key identifier string (e.g., 'tropics', 'nh_mid').

    Returns:
        Human-readable formatted region label string.
    """
    mapping = {
        "tropics": "Tropics",
        "nh_mid": "Nor. HS",
        "sh_mid": "Sou. HS",
        "global": "Global",
    }
    if region in mapping:
        return mapping[region]
    return region.replace("_", " ").title()


def load_summaries(results_dir: Path) -> Dict[str, pd.DataFrame]:
    """Load model summary evaluation CSVs from results directory.

    Args:
        results_dir: Path to directory containing evaluation CSV files.

    Returns:
        Dictionary mapping model names to loaded summary DataFrames.
    """
    csv_files = glob.glob(str(results_dir / "*.csv"))
    summaries = {}
    for fpath in csv_files:
        fname = Path(fpath).name
        if fname.startswith("physics_evaluation_"):
            parts = fname.replace("physics_evaluation_", "").replace(".csv", "").split("_")
            model_name = parts[0]
            df = pd.read_csv(fpath)
            summaries[model_name] = df
    return summaries


def get_model_baselines(
    summaries: Dict[str, pd.DataFrame],
    metric_name: str,
) -> Dict[str, float]:
    """Extract reference baseline values for a specific metric across models.

    Args:
        summaries: Dictionary mapping model names to summary DataFrames.
        metric_name: Target physical metric name to look up.

    Returns:
        Dictionary mapping model names to reference baseline metric values.
    """
    baselines = {}
    for model, df in summaries.items():
        df_metric = df[df["metric_name"] == metric_name]
        if not df_metric.empty and "ref_value" in df_metric.columns:
            ref_val = df_metric["ref_value"].dropna()
            if not ref_val.empty:
                baselines[model] = float(ref_val.iloc[0])
    return baselines


# ============================================================================
# Object-Oriented Physics Plotter
# ============================================================================

class PhysicsPlotter:
    """Object-oriented physics metric plotter and figure renderer.

    Attributes:
        config: PlotterConfig instance containing directory and style parameters.
    """

    def __init__(self, config: PlotterConfig) -> None:
        """Initialize plotter with configuration settings.

        Args:
            config: PlotterConfig instance with output path and styling rules.
        """
        self.config = config
        self.config.outdir.mkdir(parents=True, exist_ok=True)
        sns.set_theme(style=self.config.style, font_scale=1.1)

    def _get_color(self, label: str, index: int = 0) -> str:
        """Get consistent color for model or reference label.

        Args:
            label: Model or reference dataset name string.
            index: Palette fallback color index.

        Returns:
            Hex color string.
        """
        for key, color in MODEL_COLORS.items():
            if key.lower() in label.lower():
                return color
        return DEFAULT_PALETTE[index % len(DEFAULT_PALETTE)]

    def plot_time_series(
        self,
        df_ts: pd.DataFrame,
        metric_col: str,
        title: str,
        ylabel: str,
        filename: str,
        ref_val: Optional[float] = None,
    ) -> Path:
        """Render and save a time series plot with ensemble shading if available.

        Args:
            df_ts: Input time-series DataFrame containing forecast hours and values.
            metric_col: Name of column containing metric values to plot.
            title: Title header string for the generated figure.
            ylabel: Y-axis label text string.
            filename: Base filename for the saved figure file (without extension).
            ref_val: Optional horizontal reference baseline value.

        Returns:
            Path object pointing to the saved figure image file.
        """
        fig, ax = plt.subplots(figsize=(10, 5))

        if "model" in df_ts.columns:
            models = df_ts["model"].unique()
        else:
            models = ["Model"]
            df_ts["model"] = "Model"

        for idx, model_name in enumerate(models):
            df_m = df_ts[df_ts["model"] == model_name]
            color = self._get_color(model_name, idx)

            if "ensemble_member" in df_m.columns and df_m["ensemble_member"].nunique() > 1:
                stats = df_m.groupby("forecast_hour")[metric_col].agg(
                    ["mean", "std"]
                ).reset_index()
                ax.plot(
                    stats["forecast_hour"],
                    stats["mean"],
                    label=f"{model_name} (mean)",
                    color=color,
                    linewidth=2,
                )
                ax.fill_between(
                    stats["forecast_hour"],
                    stats["mean"] - stats["std"],
                    stats["mean"] + stats["std"],
                    color=color,
                    alpha=0.2,
                    label=f"{model_name} (±1 std)",
                )
            else:
                stats = df_m.groupby("forecast_hour")[metric_col].mean().reset_index()
                ax.plot(
                    stats["forecast_hour"],
                    stats[metric_col],
                    label=model_name,
                    color=color,
                    linewidth=2,
                )

        if ref_val is not None:
            ax.axhline(ref_val, color="#2c3e50", linestyle="--", linewidth=1.5, label="Reference")

        ax.set_title(title, fontsize=14, fontweight="bold", pad=12)
        ax.set_xlabel("Forecast Lead Time (hours)", fontsize=12)
        ax.set_ylabel(ylabel, fontsize=12)
        ax.legend(frameon=True, facecolor="white", framealpha=0.9)
        plt.tight_layout()

        out_path = self.config.outdir / f"{filename}.{self.config.file_format}"
        plt.savefig(out_path, dpi=self.config.dpi)
        plt.close(fig)
        return out_path

    def generate_all(self) -> List[Path]:
        """Load CSV datasets and generate all diagnostic figures.

        Returns:
            List of Path objects for all successfully generated plot files.
        """
        generated_plots: List[Path] = []
        csv_files = glob.glob(str(self.config.results_dir / "*.csv"))

        if not csv_files:
            print(f"No CSV files found in {self.config.results_dir}.")
            return generated_plots

        ts_files = [f for f in csv_files if "time_series" in Path(f).name]
        if ts_files:
            df_ts_list = [pd.read_csv(f) for f in ts_files]
            df_ts = pd.concat(df_ts_list, ignore_index=True)

            if "dry_mass_Eg" in df_ts.columns:
                p = self.plot_time_series(
                    df_ts,
                    "dry_mass_Eg",
                    "Global Dry Air Mass Drift",
                    "Dry Mass (Eg)",
                    "ts_dry_mass_Eg",
                )
                generated_plots.append(p)

            if "water_mass_kg" in df_ts.columns:
                p = self.plot_time_series(
                    df_ts,
                    "water_mass_kg",
                    "Global Water Mass Drift",
                    "Water Mass (kg)",
                    "ts_water_mass_kg",
                )
                generated_plots.append(p)

            if "total_energy_J" in df_ts.columns:
                p = self.plot_time_series(
                    df_ts,
                    "total_energy_J",
                    "Global Total Atmospheric Energy Drift",
                    "Total Energy (J)",
                    "ts_total_energy_J",
                )
                generated_plots.append(p)

            if "hydrostatic_rmse" in df_ts.columns:
                p = self.plot_time_series(
                    df_ts,
                    "hydrostatic_rmse",
                    "Hydrostatic Balance Error RMSE",
                    "RMSE (m²/s²)",
                    "ts_hydrostatic_rmse",
                )
                generated_plots.append(p)

            if "geostrophic_rmse" in df_ts.columns:
                p = self.plot_time_series(
                    df_ts,
                    "geostrophic_rmse",
                    "Geostrophic Wind Balance Error RMSE",
                    "RMSE (m/s)",
                    "ts_geostrophic_rmse",
                )
                generated_plots.append(p)

        return generated_plots


def generate_all_plots(
    results_dir: Union[str, Path],
    outdir: Union[str, Path],
    reference_label: str = "auto",
) -> List[Path]:
    """Backward-compatible wrapper function for generating diagnostic plots.

    Args:
        results_dir: Path to directory containing output CSV files.
        outdir: Destination directory for generated plots.
        reference_label: Reference dataset label override.

    Returns:
        List of Path objects pointing to generated figure files.
    """
    config = PlotterConfig(
        results_dir=Path(results_dir),
        outdir=Path(outdir),
        reference_label=reference_label,
    )
    plotter = PhysicsPlotter(config)
    return plotter.generate_all()


# ============================================================================
# CLI Command Entrypoint
# ============================================================================

def main() -> None:
    """CLI entrypoint for physmetrics-plot command."""
    parser = argparse.ArgumentParser(description="Generate diagnostic plots for physics metrics")
    parser.add_argument(
        "--results-dir",
        type=str,
        default=str(Path.cwd() / "results"),
        help="Path to results directory.",
    )
    parser.add_argument(
        "--outdir",
        type=str,
        default=str(Path.cwd() / "plots"),
        help="Path to output plots directory.",
    )
    parser.add_argument(
        "--reference-label",
        type=str,
        default="auto",
        help="Reference label override.",
    )
    args = parser.parse_args()

    plots = generate_all_plots(args.results_dir, args.outdir, reference_label=args.reference_label)
    print(f"Generated {len(plots)} plot(s) in {args.outdir}")


if __name__ == "__main__":
    main()
